spring:
  application:
    name: activityservice

server:
  port:
    8082

  data:
    mongodb:
      uri: mongodb+srv://Shreyansh:Pass123@cluster01.or3ecas.mongodb.net/fitnessApp_activities?authSource=admin&appName=Cluster01

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
